
title: 
url: 'https://takagotch.github.io/page81/'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Takashi Yoshioka  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: Namba Osaka , JP


## Social Profiles
facebook: http://www.facebook.com/takagotch ## your facebook account url
twitter: http://www.twitter.com/takagotch  ## your twitter account url
linkedin: http://www.linkedin.com/takagotch  ## your linkedin account url
dribbble: http://www.dribble.com/takagotch  ## you dribbble account url
foursquare: http://www.foursquare.com/takagotch  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
